name: testssl.sh CI

on:
  pull_request:
    paths-ignore:
      - 'utils/**'
      - 'doc/**'
      - 'bin/**'
      - '**.md'
      - '**.pem'
      - '**.pdf'
      - '**.html'
      - 'LICENSE'
      - 'Dockerfile'
      - 'Dockerfile-alpine'

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14
    name: Testing unit test on MacOS
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl etc
      - run: brew install perl curl socat
      - run: perl -V
      - name: Install deps
        run: sudo apt install dnsutils jsonlint
      - run: cpanm --notest Test::More
      - run: cpanm --notest Data::Dumper
      - run: cpanm --notest JSON
      - run: cpanm --notest Text::Diff
      - run: prove -v
