name: testssl.sh CI

on:
  pull_request:
    paths-ignore:
      - 'utils/**'
      - 'doc/**'
      - 'bin/**'
      - '**.md'
      - '**.pem'
      - '**.pdf'
      - '**.html'
      - 'LICENSE'
      - 'Dockerfile'
      - 'Dockerfile-alpine'

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14
    name: Testing unit test on MacOS
    steps:
      - uses: actions/checkout@v4

      - name: Set up perl etc
        run: |
          brew install perl curl socat jsonlint
          perl -V

      - name: install perl modules
        run: |
          cpanm --notest Test::More
          cpanm --notest Data::Dumper
          cpanm --notest JSON
          cpanm --notest Text::Diff

      -name: run it
       run: |
            prove -v
