---
name: testssl.sh CI with MacOS

on:
  pull_request:
    paths-ignore:
      - 'utils/**'
      - 'doc/**'
      - 'bin/**'
      - '**.md'
      - '**.pem'
      - '**.pdf'
      - '**.html'
      - 'LICENSE'
      - 'Dockerfile'
      - 'Dockerfile-alpine'

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14

    name: PoC unit test on MacOS
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up system (perl, curl is installed already)
        run: |
          brew install socat jsonlint cpanminus
          mv /opt/homebrew/bin/openssl /opt/homebrew/bin/openssl.NOPE
          printf "----------\n"
          perl -V
          printf "----------\n"
          curl --version
          printf "----------\n"
          openssl version -a
          printf "----------\n"
          bash --version
          printf "----------\n"

      - name: install perl modules
        run: |
          cpanm --notest Test::More
          cpanm --notest Data::Dumper
          cpanm --notest JSON
          cpanm --notest Text::Diff

      - name: run it
        run: |
            prove -v
